name: Duels
api: [4.2.0]
version: 1.0.0
main: vixikhd\duels\Duels
author: SunshroomChan
description: Simplfy 1v1 plugins with new features
depends: [Scoreboards]

extensions: [mysqli, yaml, json, zip]

permissions:
  duels.cmd:
    description: Permission to all SkyWars commands
    default: op
  duels.cmd.help:
    description: Permission for /duels help
    default: op
  duels.cmd.create:
    description: Permission for /duels create
    default: op
  duels.cmd.remove:
    description: Permission for /duels remove
    default: op
  duels.cmd.set:
    description: Permission for /duels set
    default: op
  duels.cmd.arenas:
    description: Permission for /duels arenas
    default: op
  duels.cmd.start:
    description: Permission for /duels start
    default: op
  duels.cmd.test:
    description: Permission for /duels test
    default: true
  duels.cmd.win:
    description: Permission for /duels win
    default: true
  duels.cmd.kick:
    description: Permission for /duels kick
    default: op
  duels.cmd.leave:
    description: Permission for /duels leave
    default: true
  duels.cmd.join:
    description: Permission for /duels join
    default: true
  duels.cmd.random:
        description: Permission for /duels random
        default: true
